<template>
  <q-card>
    <q-card-section>
      <div class="q-gutter-sm">
        <div class="text-bold">What do you want to write about?</div>
        <q-input
          label="Article topic"
          hint="Examples: petition, protest march, Extinction Rebellion"
          v-model="topic"
        />
        <div>
          <q-radio v-model="type" val="tactic" label="Tactic" />
          <q-radio v-model="type" val="book" label="Book" />
          <q-radio v-model="type" val="movie" label="Movie" />
          <q-radio v-model="type" val="movement" label="Movement" />
        </div>
        <q-card bordered flat>
          <q-card-section>
            <div class="text-caption">Usage terms</div>
            <div class="text-bold">
              This text is generated by artificial intelligence (powered by
              OpenAI, Davinci model). You may not publish this text anywhere
              without proofreading and factchecking everything. Only use this
              tool to get inspiration for writing your articles. In addition,
              you must adhere to the
              <a href="https://beta.openai.com/docs/usage-guidelines"
                >OpenAI usage guidelines</a
              >.
            </div>
            <q-checkbox
              v-model="consent"
              label="I understand and consent to the usage terms."
            />
          </q-card-section>
        </q-card>
        <q-btn
          color="primary"
          label="Generate text"
          @click="generateText()"
          :disable="!topic || !consent"
          no-caps
          :loading="dataLoading || (!dataLoading && $store.state.result.data)"
        />
      </div>
    </q-card-section>
  </q-card>
</template>
<script>
import { httpsCallable } from "firebase/functions";
import { doc, onSnapshot, getFirestore } from "firebase/firestore";
const db = getFirestore();

export default {
  data() {
    return {
      consent: false,
      dataLoading: false,
      topic: "",
      type: "tactic",
    };
  },
  methods: {
    generateText() {
      this.dataLoading = true;

      const testFunction = httpsCallable(
        this.$store.state.firebase.functions,
        "testFunction"
      );
      const id = this.makeid();
      testFunction({ id: id, type: this.type, topic: this.topic })
        .then((result) => {
          onSnapshot(doc(db, "results", id), (doc) => {
            this.$store.commit("result/addResult", doc.data());
            this.dataLoading = false;
          });
        })
        .catch((error) => {
          console.log(error);
        });
    },
    makeid() {
      var result = "";
      var characters =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
      var charactersLength = characters.length;
      for (var i = 0; i < 30; i++) {
        result += characters.charAt(
          Math.floor(Math.random() * charactersLength)
        );
      }
      return result;
    },
  },
};
</script>
