<template>
  <q-card>
    <q-card-section>
      <div class="q-gutter-sm">
        <div class="text-bold">What do you want to write about?</div>
        <q-input label="Topic" />
        <div>
          <q-radio v-model="type" val="tactic" label="Tactic" />
          <q-radio v-model="type" val="book" label="Book" />
          <q-radio v-model="type" val="movie" label="Movie" />
          <q-radio v-model="type" val="movement" label="Movement" />
        </div>
        <q-card bordered flat>
          <q-card-section>
            <div class="text-caption">Usage terms</div>
            <div class="text-bold">
              This text is generated by artificial intelligence (powered by
              OpenAI, Davinci model). You may not publish this text anywhere
              without proofreading and factchecking everything. Only use this
              tool to get inspiration for writing your articles. In addition,
              you must adhere to the
              <a href="https://beta.openai.com/docs/usage-guidelines"
                >OpenAI usage guidelines</a
              >.
            </div>
            <q-checkbox
              v-model="consent"
              label="I understand and consent to the usage terms."
            />
          </q-card-section>
        </q-card>
        <q-btn color="primary" label="Generate text" />
      </div>
    </q-card-section>
  </q-card>
</template>
<script>
export default {
  data() {
    return {
      consent: false,
      type: "tactic",
    };
  },
};
</script>
